export default {
  FONT_SIZE_HEADER: 64,
  FONT_SIZE_LARGE: 32,
  FONT_SIZE_MEDIUM: 18,
  FONT_SIZE_SMALL: 14,
  PRIMARY_COLOR: '#30292F',
  SECONDARY_COLOR: '#8E9AAF',
  BUTTON_PRIMARY_COLOR: '#236B35',
  OFF_COLOR: '#B14437',
  WHITE: '#FFFFFF',
  STANDARD_MARGIN: 10,
  STANDARD_MARGIN_LARGE: 15,
};
